import SECTION from './section'
import PAGE from './page'

export const MENU_LIST = {
  MAIN: { TITLE: SECTION.MAIN.TITLE, ID: `/${SECTION.MAIN.ID}` },
  ABOUT: { TITLE: SECTION.ABOUT.TITLE, ID: `/${SECTION.ABOUT.ID}` },
  BLOG: { TITLE: SECTION.BLOG.TITLE, ID: `/${SECTION.BLOG.ID}` },
  DOCUMENT: { TITLE: SECTION.DOCUMENT.TITLE, ID: `/${SECTION.DOCUMENT.ID}` },
  CAREER: { TITLE: PAGE.CAREER.TITLE, ID: PAGE.CAREER.PATH },
  SKILL: { TITLE: PAGE.SKILL.TITLE, ID: PAGE.SKILL.PATH },
  CONTACT: { TITLE: SECTION.CONTACT.TITLE, ID: PAGE.CONTACT.PATH },
} as const

export const MENU = Object.values(MENU_LIST)
